name: Test the application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install denpendecies
        run: npm install

      - name: Run Prettier
        run: npm run format:verify

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test
